// authentication
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';

// project
export const PROJECT_LOADED = 'PROJECT_LOADED';
export const PROJECT_LOADING = 'PROJECT_LOADING';
export const PROJECT_UPDATED = 'PROJECT_UPDATED';
export const PROJECT_USER_SIGNIN = 'PROJECT_USER_SIGNIN';
export const PROJECT_USER_SIGNOUT = 'PROJECT_USER_SIGNOUT';
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const ASSIGNE_BADGE = 'ASSIGNE_BADGE';
export const UNASSIGNE_BADGE = 'UNASSIGNE_BADGE';
export const ASSIGNE_MULTIPLE_BADGES = 'ASSIGNE_MULTIPLE_BADGES';
export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const SET_PROJECT_PARAMS = 'SET_PROJECT_PARAMS';

// messages
export const GET_ERRORS = 'GET_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

// badge
export const GET_BADGES = 'GET_BADGES';
export const ADD_BADGE = 'ADD_BADGE';
export const CHANGE_BADGE = 'CHANGE_BADGE';
export const CHANGE_BADGES = 'CHANGE_BADGES';
export const BADGES_LOADING = 'BADGES_LOADING';
export const DEACTIVATE_BADGE = 'DEACTIVATE_BADGE';
export const NOMINATE_ISSUER = 'NOMINATE_ISSUER';
export const ACCEPT_MENTOR = 'ACCEPT_MENTOR';
export const DECLINE_MENTOR = 'DECLINE_MENTOR';
export const REQUEST_BADGE_PERMISSION = 'REQUEST_BADGE_PERMISSION';
export const SET_BADGE_PARAMS = 'SET_BADGE_PARAMS';

// helper
export const SET_PANEL = 'SET_PANEL';
