// authentication
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';

// course
export const COURSE_LOADED = 'COURSE_LOADED';
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_UPDATED = 'COURSE_UPDATED';
export const COURSE_USER_SIGNIN = 'COURSE_USER_SIGNIN';
export const COURSE_USER_SIGNOUT = 'COURSE_USER_SIGNOUT';
export const COURSES_LOADED = 'COURSES_LOADED';
export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSE_ERROR = 'COURSE_ERROR';
export const SET_COURSE_PARAMS = 'SET_COURSE_PARAMS';

// messages
export const GET_ERRORS = 'GET_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

// badge
export const GET_BADGES = 'GET_BADGES';
export const ADD_BADGE = 'ADD_BADGE';
